package com.core.bingehaven.enums;

import lombok.Getter;

@Getter
public enum BnhKeywords {
    ACTION_HERO("action-hero"),
    ALIEN_INVASION("alien-invasion"),
    ALTERNATE_HISTORY("alternate-history"),
    ANIME("anime"),
    ANTI_HERO("anti-hero"),
    AVANT_GARDE("avant-garde"),
    B_MOVIE("b-movie"),
    BANK_ROBBERY("bank-robbery"),
    BASED_ON_BOOK("based-on-book"),
    BASED_ON_COMIC_BOOK("based-on-comic-book"),
    BASED_ON_NOVEL("based-on-novel"),
    BASED_ON_PLAY("based-on-play"),
    BASED_ON_TRUE_STORY("based-on-true-story"),
    BECHDEL_TEST_PASSED("bechdel-test-passed"),
    BLACK_COMEDY("black-comedy"),
    BOLLYWOOD("bollywood"),
    CAPER("caper"),
    CHICK_FLICK("chick-flick"),
    COMING_OF_AGE("coming-of-age"),
    CONSPIRACY("conspiracy"),
    CRIMINAL_MASTERMIND("criminal-mastermind"),
    CULT_FILM("cult-film"),
    CYBERPUNK("cyberpunk"),
    DARK_FANTASY("dark-fantasy"),
    DC_COMICS("dc-comics"),
    DYSTOPIA("dystopia"),
    EPIC("epic"),
    ESPIONAGE("espionage"),
    EXPERIMENTAL_FILM("experimental-film"),
    F_RATED("f-rated"),
    FAIRY_TALE("fairy-tale"),
    FEMME_FATALE("femme-fatale"),
    FUTURISTIC("futuristic"),
    GOOD_VERSUS_EVIL("good-versus-evil"),
    HAUNTING("haunting"),
    HEIST("heist"),
    HIGH_SCHOOL("high-school"),
    INDEPENDENT_FILM("independent-film"),
    KIDNAPPING("kidnapping"),
    KUNG_FU("kung-fu"),
    LGBTQ("lgbtq"),
    MAGICAL_REALISM("magical-realism"),
    MARVEL_COMICS("marvel-comics"),
    MOCKUMENTARY("mockumentary"),
    MONSTER("monster"),
    ON_THE_RUN("on-the-run"),
    ONE_MAN_ARMY("one-man-army"),
    PARALLEL_WORLD("parallel-world"),
    PARANORMAL_PHENOMENON("paranormal-phenomenon"),
    PARENTHOOD("parenthood"),
    PARODY("parody"),
    POLICE_DETECTIVE("police-detective"),
    POST_APOCALYPSE("post-apocalypse"),
    POSTMODERN("postmodern"),
    REDEMPTION("redemption"),
    RESCUE("rescue"),
    ROAD_MOVIE("road-movie"),
    ROBBERY("robbery"),
    SATIRE("satire"),
    SEQUEL("sequel"),
    SPACE_TRAVEL("space-travel"),
    SPAGHETTI_WESTERN("spaghetti-western"),
    SPOOF("spoof"),
    STEAMPUNK("steampunk"),
    SUPERHERO("superhero"),
    SUPERNATURAL_POWER("supernatural-power"),
    SWASHBUCKLER("swashbuckler"),
    TIME_TRAVEL("time-travel"),
    TRIPLE_F_RATED("triple-f-rated"),
    VAMPIRE("vampire"),
    ZOMBIE("zombie");

    private final String keyword;

    BnhKeywords(String keyword) {
        this.keyword = keyword;
    }

}
